vuni/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "VUniReg - Administration"

urlpatterns = [
	path('', include('vunireg.urls')),
    path('admin/', admin.site.urls),
]

vunireg/urls.py
from django.urls import path, include, re_path
from django.conf.urls import url, include

from . import views

app_name = 'vunireg'
urlpatterns = [
    path('', views.index, name='index'),
    url('home', views.home, name="home"),
    path('test', views.test, name='test'),
    path('add/', views.event_add, name='event_add'),
    path('<event_id>/event/', views.event, name='event'),
    path('<event_id>/event/eventdata/', views.event_edit_eventdata, name='event_edit_eventdata'),
    path('<event_id>/event/competition/', views.event_edit_competition, name='event_edit_competition'),
    path('<event_id>/event/scoringcategory/<scoringcat_id>', views.event_edit_scoringcat, name='event_edit_scoringcat'),
    path('<event_id>/event/qualification/<qualification_id>', views.event_edit_qualification, name='event_edit_qualification'),
    path('<event_id>/entry/', views.entrys, name='entrys'),
    path('<event_id>/entrys/teilnehmer/', views.person_list, name='person_list'),
    path('<event_id>/entrys/teilnehmer/import/', views.person_csv, name='person_csv'),
    path('<event_id>/entrys/teilnehmer/add/', views.person_add, name='person_add'),
    path('<event_id>/entrys/teilnehmer/editm/<person_id>/', views.person_editm, name='person_editm'),
    path('<event_id>/entrys/teams/', views.entrys_team_list, name='entrys_team_list'),
    path('<event_id>/entrys/team/edit/<team_id>', views.entrys_team_edit, name='entrys_team_edit'),
    path('<event_id>/entrys/clubs/', views.club_list, name='club_list'),
    path('<event_id>/entrys/club/edit/<club_id>', views.entrys_club_edit, name='entrys_club_edit'),
    path('<event_id>/entrys/club/merge/<club1_id>/<club2_id>', views.entrys_club_merge, name='entrys_club_merge'),
    path('<event_id>/entrys/meldungen/', views.entrys_entry_list, name='entrys_entry_list'),
    path('<event_id>/starts/', views.start, name='start'),
    path('<event_id>/starts/competition/', views.competition_list, name='competition_list'),
    path('<event_id>/starts/competition/?del=<competition_id>', views.del_singlecompetition, name='del_singlecompetition'),
    path('<event_id>/starts/competition/?merge=<competition_id>', views.merge_singlecompetition, name='merge_singlecompetition'),
    path('<event_id>/starts/competition/calc_entry', views.competition_list, name='competition_list'),
    path('<event_id>/starts/startnr/', views.start_startnr, name='start_startnr'),
    path('<event_id>/starts/startnr?del=<person_id>', views.startnr_clr, name='startnr_clr'),
    path('<event_id>/starts/seeding/', views.start_seed_overview, name='start_seed_overview'),
    path('<event_id>/starts/seeding/<discipline_id>', views.start_seed_listview, name='start_seed_listview'),
    path('<event_id>/execution/', views.execution, name='execution'),
    path('<event_id>/execution/results/show/<scoringcat_id>/<discipline_id>', views.execution_show_result, name='execution_show_result'),
    path('<event_id>/execution/results/edit/<competition_id>', views.execution_edit_result, name='execution_edit_result'),
    path('<event_id>/execution/results/import/', views.import_result_csv, name='import_result_csv'),
    path('<event_id>/execution/results/print_resultlist/<scoringcat_id>/<discipline_id>', views.print_resultlist, name='print_resultlist'),
    path('<event_id>/execution/results/print_compcert/<club_id>', views.print_compcert_pdf, name='print_compcert_pdf'),
    path('pdf/', views.generate_pdf, name='generate_pdf'),
    path('urkunde/', views.generate_certificate_pdf, name='generate_certificate_pdf'),
    path('<event_id>/infield/iuf/<start_id>', views.infield_iuf_slalom, name='infield_iuf_slalom'),
    path('infield_serialsend', views.infield_serialsend, name='infield_serialsend'),
    path('infield_serialread', views.infield_serialread, name='infield_serialread'),
]

#(?P<pk>\d+)/$

templates/base.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!--  include "templates/header.html"  in header.html:  extends "base.html"  --!>
  <head>
    <!-- Required meta tags -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<!--
    <style>
      .navbar { margin-bottom: 1rem; }
      tr.canceled td, tr td.canceled { font-style: italic; background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWP4JST0HwAFRgIefzRCKwAAAABJRU5ErkJggg=='); background-repeat: repeat-x; background-position: 50% 50%; }
    </style>
--!>    
    {% block stylesheets %}{% endblock %}
    <!-- Seitentitel -->
    <title>{% block title %}VUniReg{% endblock %}</title>
  </head>
  
  <body>
  <div class="flex">
  
    <div class="menu-wrap">
        <nav class="container no-list">
        
            <!-- [THE HAMBURGER] -->
                <input type="checkbox" id="hamburger">
                <label for="hamburger" class="hamburger">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                </label>
    
            <!-- [MENU ITEMS] -->
            <ul id="main-menu">
                <li>
                    <input type="checkbox" id="nav_1_1" class="open-sub-menu">
                    <label for="nav_1_1" class="sub-menu-button">
                        <i class="icon-right-open"></i>
                    </label>
                    <a href="{% url 'vunireg:event' event_id=event.pk %}">Wettkampf</a>
                    <ul class="no-list">
                        <li><a href="{% url 'vunireg:event_edit_eventdata' event_id=event.pk %}">Wettkampfdaten</a></li>
                        <li><a href="{% url 'vunireg:event_edit_scoringcat' event_id=event.pk scoringcat_id=None %}">Wertungen</a></li>
                        <li><a href="{% url 'vunireg:event_edit_competition' event_id=event.pk %}">Wettbewerbe</a></li>
                        <li><a href="{% url 'vunireg:event_edit_qualification' event_id=event.pk qualification_id=None %}">Qualifikationen</a></li>
                    </ul>
                </li>
                <li>
                    <input type="checkbox" id="nav_1_2" class="open-sub-menu">
                    <label for="nav_1_1" class="sub-menu-button">
                        <i class="icon-right-open"></i>
                    </label>
                    <a href="{% url 'vunireg:entrys' event_id=event.pk %}">Meldungen</a>
                    <ul class="no-list">
                        <li><a href="{% url 'vunireg:person_list' event_id=event.pk %}">Teilnehmer verwalten</a></li>
                        <li><a href="{% url 'vunireg:entrys_team_list' event_id=event.pk %}">Staffeln verwalten</a></li>
                        <li><a href="{% url 'vunireg:club_list' event_id=event.pk %}">Vereine verwalten</a></li>
<!--                        <li><a href="{% url 'vunireg:entrys_entry_list' event_id=event.pk %}">Meldungs Liste</a></li>          --!>
                    </ul>
                </li>
                <li>
                    <input type="checkbox" id="nav_1_3" class="open-sub-menu">
                    <label for="nav_1_2" class="sub-menu-button">
                        <i class="icon-right-open"></i>
                    </label>
                    <a href="{% url 'vunireg:start' event_id=event.pk %}">Starts</a>
                    <ul class="no-list">
                        <li><a href="{% url 'vunireg:competition_list' event_id=event.pk %}">Wettbewerbe zusammenlegen</a></li>
                        <li><a href="{% url 'vunireg:start_startnr' event_id=event.pk %}">Startnummern zuweisen</a></li>
                        <li><a href="{% url 'vunireg:start_seed_overview' event_id=event.pk %}">Starts setzten</a></li>
                    </ul>
                </li>
                <li>
                    <input type="checkbox" id="nav_1_4" class="open-sub-menu">
                    <label for="nav_1_3" class="sub-menu-button">
                        <i class="icon-right-open"></i>
                    </label>
                    <a href="{% url 'vunireg:execution' event_id=event.pk %}">Durchführung</a>
                    <ul class="no-list">
                        <li><a href="{% url 'vunireg:execution_edit_result' event_id=event.pk competition_id=None %}">Ergebnis Eingabe</a></li>
                        <li><a href="{% url 'vunireg:execution_show_result' event_id=event.pk scoringcat_id=None discipline_id=None %}">Ergebnis Übersicht</a></li>
                        <li><a href="#">Urkunden</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>

    <div class="maincontent clerafix">
<!--
        <figure class="clearfix">
            <div class="image-container">
                <img src="test.jpg" alt="Titel">
                <div class="breadcrumb-box">
                    <ul class="no-list breadcrumb inline-list">
                        <li>
                            <a href="#"><b>Start</b></a>
                            ›
                        </li>
                        <li>
                            <a href="#">Breadcrumb Navigation</a>
                        </li>
                    </ul>
                </div>
                <div class="headline">
                    <h1>
                        <strong>Seitentitel</strong>
                    </h1>
                </div>
            </div>
        </figure>
--!>
        <div class="row content clearfix">        
            {% block content %}{% endblock %}
        </div>
    </div>


    <footer>
        <div class="no-list container clearfix">
<!--        
            <ul class="no-list pull-right inline-list">
                <li><a href="#">Infos zur Software</a></li>
                <li><a href="#">Vocke Unicycling</a></li>
                <li><a href="#">Kontakt</a></li>
            </ul>
--!>            
            <div class="no-list pull-left inline-list">
                <p>© 2021 VockeUnicycling - VUni Competition Manager 1.0.1021</p>
            </div>
        </div>
    </footer>

    {% block javascripts %}{% endblock %}
    </div>
    
    <div id="toplink">
        <div class="backtotop-icon">
            <a href="#top" style="display: block; height: 38px;"><i class="icon-up-open-big" style="padding-top: 10px; display: block;"></i></a>
        </div>
    </div>
    
    </body>
</html>

templates/index.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!--  include "templates/header.html"  in header.html:  extends "base.html"  --!>
  <head>
    <!-- Required meta tags -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<!--
    <style>
      .navbar { margin-bottom: 1rem; }
      tr.canceled td, tr td.canceled { font-style: italic; background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWP4JST0HwAFRgIefzRCKwAAAABJRU5ErkJggg=='); background-repeat: repeat-x; background-position: 50% 50%; }
    </style>
--!>    
    {% block stylesheets %}{% endblock %}
    <!-- Seitentitel -->
    <title>{% block title %}VUniReg{% endblock %}</title>
  </head>
  
  <body>
  <div>
  
  <header class="clearfix">
  
<!--  
        <section id="topmenu" class="no-list container clearfix">
            <a class="pull-left logo" href="#">
                <img src="logo-vuni.jpg" alt="Logo VockeUnicycling"></img>
            </a>
            <div class="no-list pull-right inline-list">
                <form class="search-form" id="search_it-form1" action="./index.php?article_id=11" method="get">
                    <fieldset>
                        <legend>{{ Suche }}</legend>
                        <label for="search">{{ Suchbegriff }}</label>
                        <input name="article_id" value="11" type="hidden">
                        <input name="clang" value="1" type="hidden">
                        <input name="search" class="search" value="" placeholder="Suche" type="text">
                        <button type="submit" class="search-icon" aria-label="Submit Search">
                            <i class="icon-search"></i>
                        </button>
                    </fieldset>
                </form>
            </div>
        </section>
--!>

    </header>
  
    <div class="menu-wrap">
        <nav class="container no-list">
        
            <!-- [THE HAMBURGER] -->
                <input type="checkbox" id="hamburger">
                <label for="hamburger" class="hamburger">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                </label>
    
            <!-- [MENU ITEMS] -->
            <ul id="main-menu">
                <li>
                    <input type="checkbox" id="nav_1_1" class="open-sub-menu">
                    <label for="nav_1_1" class="sub-menu-button">
                        <i class="icon-right-open"></i>
                    </label>
                    <a href="{% url 'vunireg:index' %}">Wettkampf Wählen</a>
                </li>
            </ul>
        </nav>
    </div>

    <div class="maincontent clerafix">
<!--
        <figure class="clearfix">
            <div class="image-container">
                <img src="test.jpg" alt="Titel">
                <div class="breadcrumb-box">
                    <ul class="no-list breadcrumb inline-list">
                        <li>
                            <a href="#"><b>Start</b></a>
                            ›
                        </li>
                        <li>
                            <a href="#">Breadcrumb Navigation</a>
                        </li>
                    </ul>
                </div>
                <div class="headline">
                    <h1>
                        <strong>Seitentitel</strong>
                    </h1>
                </div>
            </div>
        </figure>
--!>
        <div class="row content clearfix">
            {% block content %}{% endblock %}
        </div>
    </div>


    <footer>
        <div class="no-list container clearfix">
<!--        
            <ul class="no-list pull-right inline-list">
                <li><a href="#">Infos zur Software</a></li>
                <li><a href="#">Vocke Unicycling</a></li>
                <li><a href="#">Kontakt</a></li>
            </ul>
--!>            
            <div class="no-list pull-left inline-list">
                <p>© 2020 VockeUnicycling</p>
            </div>
        </div>
    </footer>

    {% block javascripts %}{% endblock %}
    </div>
    
    <div id="toplink">
        <div class="backtotop-icon">
            <a href="#top" style="display: block; height: 38px;"><i class="icon-up-open-big" style="padding-top: 10px; display: block;"></i></a>
        </div>
    </div>
    
    </body>
</html>

templates/infield_base.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!--  include "templates/header.html"  in header.html:  extends "base.html"  --!>
  <head>
    <!-- Required meta tags -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- JS -->
    <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>

    
    <script language="JavaScript">
<!--
var startTime = 0
var start = 0
var end = 0
var diff = 0
var timerID = 0
var timerID2 = 0
function chrono(){
	end = new Date()
	diff = end - start
	diff = new Date(diff)
	var msec = diff.getMilliseconds()
	var msecr = Math.ceil(msec/10)
	var sec = diff.getSeconds()
	var min = diff.getMinutes()
	if(msecr > 99){
		msecr = "00"
		sec = sec + 1
	}
	else if(msecr < 10){
		msecr = "0" + msecr
	}
	if (sec < 10){
		sec = "0" + sec
	}
	document.getElementById("chronotime").innerHTML = min + "." + sec + ":" + msecr
	document.getElementById("inputchronotime").value = min + "." + sec + ":" + msecr
	timerID = setTimeout("chrono()", 200)
	readSerial()
}
function chronoStart(){
	document.chronoForm.startstop.value = "stop"
	document.chronoForm.startstop.onclick = chronoStop
	document.chronoForm.reset.onclick = chronoReset
	document.getElementById("unload_person").disabled = true
	document.getElementById("unload_person").classList.add("disabled")
	document.chronoForm.resettimer.disabled = true
	document.chronoForm.resettimer.classList.add("disabled")
	start = new Date()
	chrono()
}
function chronoContinue(){
	document.chronoForm.startstop.value = "stop"
	document.chronoForm.startstop.onclick = chronoStop
	document.chronoForm.reset.onclick = chronoReset
	start = new Date()-diff
	start = new Date(start)
	chrono()
}
function chronoReset(){
	document.getElementById("chronotime").innerHTML = "0.00:00"
	document.getElementById("unload_person").disabled = false
	document.getElementById("unload_person").classList.remove("disabled")
	document.chronoForm.startstop.value = "start"
	document.chronoForm.startstop.onclick = function() {chronoStart(); sendSerial();}
	document.chronoForm.reset.onclick = chronoReset
	document.chronoForm.resettimer.disabled = true
	document.chronoForm.resettimer.classList.add("disabled")
	start = new Date()
}
function chronoStopReset(){
	document.getElementById("chronotime").innerHTML = "0.00:00"
	document.chronoForm.startstop.onclick = chronoStart
}
function chronoStop(){
	document.chronoForm.startstop.value = "start"
	document.chronoForm.startstop.onclick = chronoContinue
	document.chronoForm.resettimer.disabled = false
	document.chronoForm.resettimer.classList.remove("disabled")
	clearTimeout(timerID)
}

function saveResult(){
	var input_min = document.chronoForm.input_min.value
	var input_sec = document.chronoForm.input_s.value
	var input_msec = document.chronoForm.input_ms.value
	document.getElementById("inputchronotime").value = input_min + "." + input_sec + ":" + input_msec
	document.getElementById("timetosave").innerHTML = input_min + "." + input_sec + ":" + input_msec
}
function sendSerial(){
    data = document.chronoForm.startstop.value
    console.log(new Date() + ' - Funktion sendSerial aufgerufen')
    console.log(data)
    $.get("{% url 'vunireg:infield_serialsend' %}", {"data":data})
//     $.ajax({
//         type: 'GET',
//         url: "{% url 'vunireg:infield_serialsend' %}",
//         data: {"value":data},
//         success: function (response) {
//             console.log('Success')
//         }
//         error: function (response) {
//             console.log('Error')
//         }
//     })
}
function readSerial(){
    console.log(new Date() + ' - Funktion readSerial aufgerufen')
    $.get("{% url 'vunireg:infield_serialread' %}").done(function(response){
        console.log(response)
        if(response != '') {
            clearTimeout(timerID)
            document.getElementById("chronotime").innerHTML = response
            document.getElementById("inputchronotime").value = response
        }
//        if(response == 'Time:\n') {
//            $.get("{% url 'vunireg:infield_serialread' %}").done(function(response){
//                console.log(response)
//                document.getElementById("chronotime").innerHTML = response
//            })
//        }
    })
}
//-->
</script>
<!--
    <style>
      .navbar { margin-bottom: 1rem; }
      tr.canceled td, tr td.canceled { font-style: italic; background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWP4JST0HwAFRgIefzRCKwAAAABJRU5ErkJggg=='); background-repeat: repeat-x; background-position: 50% 50%; }
    </style>
--!>    
    {% block stylesheets %}{% endblock %}
    <!-- Seitentitel -->
    <title>{% block title %}VUniReg{% endblock %}</title>
  </head>
  
  <body>
  <div class="flex">
  
    <div class="menu-wrap">
        <nav class="container no-list">
        
            <!-- [THE HAMBURGER] -->
                <input type="checkbox" id="hamburger">
                <label for="hamburger" class="hamburger">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                </label>
    
            <!-- [MENU ITEMS] -->
            <ul id="main-menu" style="justify-content: space-between">
                <li>
                    <input type="checkbox" id="nav_1_1" class="open-sub-menu">
                    <label for="nav_1_3" class="sub-menu-button">
                        <i class="icon-right-open"></i>
                    </label>
                    <a href="{ url 'vunireg:infield' event_id=event.pk }">Logout</a>
                </li>
            </ul>
        </nav>
    </div>

    <div class="maincontent clerafix">
<!--
        <figure class="clearfix">
            <div class="image-container">
                <img src="test.jpg" alt="Titel">
                <div class="breadcrumb-box">
                    <ul class="no-list breadcrumb inline-list">
                        <li>
                            <a href="#"><b>Start</b></a>
                            ›
                        </li>
                        <li>
                            <a href="#">Breadcrumb Navigation</a>
                        </li>
                    </ul>
                </div>
                <div class="headline">
                    <h1>
                        <strong>Seitentitel</strong>
                    </h1>
                </div>
            </div>
        </figure>
--!>
        <div class="row content clearfix">        
            {% block content %}{% endblock %}
        </div>
    </div>


    <footer>
        <div class="no-list container clearfix">
<!--        
            <ul class="no-list pull-right inline-list">
                <li><a href="#">Infos zur Software</a></li>
                <li><a href="#">Vocke Unicycling</a></li>
                <li><a href="#">Kontakt</a></li>
            </ul>
--!>            
            <div class="no-list pull-left inline-list">
                <p>© 2020 VockeUnicycling - VUni Competition Manager 1.0.1020</p>
            </div>
        </div>
    </footer>

    {% block javascripts %}{% endblock %}
    </div>

<!--     
    <div id="toplink">
        <div class="backtotop-icon">
            <a href="#top" style="display: block; height: 38px;"><i class="icon-up-open-big" style="padding-top: 10px; display: block;"></i></a>
        </div>
    </div>
--!>
    
    </body>
</html>

templates/person.html
{% block 2ndMenuLevel %}
<div class="menu-wrap">
    <nav class="container no-list">

        <!-- [MENU ITEMS] -->
        <ul id="main-menu">
            <li>
                <input type="checkbox" id="nav_1_1" class="open-sub-menu">
                <label for="nav_1_1" class="sub-menu-button">
                    <i class="icon-right-open"></i>
                </label>
                <a href="{% url 'vunireg:event' event_id=event.pk %}">Meldungen</a>
            </li>
            <li>
                <input type="checkbox" id="nav_1_2" class="open-sub-menu">
                <label for="nav_1_1" class="sub-menu-button">
                    <i class="icon-right-open"></i>
                </label>
                <a href="{% url 'vunireg:event' event_id=event.pk %}">Staffeln</a>
            </li>
            <li>
                <input type="checkbox" id="nav_1_2" class="open-sub-menu">
                <label for="nav_1_1" class="sub-menu-button">
                    <i class="icon-right-open"></i>
                </label>
                <a href="{% url 'vunireg:event' event_id=event.pk %}">CSV-Im-/Export</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}