vuni/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header = "VUniReg - Administration"

urlpatterns = [
	path('', include('vunireg.urls')),
    path('admin/', admin.site.urls),
]

vunireg/urls.py
from django.urls import path, include, re_path
from django.conf.urls import url, include

from . import views

app_name = 'vunireg'
urlpatterns = [
    path('', views.index, name='index'),
    url('home', views.home, name="home"),
    path('test', views.test, name='test'),
    path('add/', views.event_add, name='event_add'),
    path('<event_id>/event/', views.event, name='event'),
    path('<event_id>/event/eventdata/', views.event_edit_eventdata, name='event_edit_eventdata'),
    path('<event_id>/event/competition/', views.event_edit_competition, name='event_edit_competition'),
    path('<event_id>/event/scoringcategory/<scoringcat_id>', views.event_edit_scoringcat, name='event_edit_scoringcat'),
    path('<event_id>/event/qualification/<qualification_id>', views.event_edit_qualification, name='event_edit_qualification'),
    path('<event_id>/entry/', views.entrys, name='entrys'),
    path('<event_id>/entrys/teilnehmer/', views.person_list, name='person_list'),
    path('<event_id>/entrys/teilnehmer/import/', views.person_csv, name='person_csv'),
    path('<event_id>/entrys/teilnehmer/add/', views.person_add, name='person_add'),
    path('<event_id>/entrys/teilnehmer/editm/<person_id>/', views.person_editm, name='person_editm'),
    path('<event_id>/entrys/teams/', views.entrys_team_list, name='entrys_team_list'),
    path('<event_id>/entrys/team/edit/<team_id>', views.entrys_team_edit, name='entrys_team_edit'),
    path('<event_id>/entrys/clubs/', views.club_list, name='club_list'),
    path('<event_id>/entrys/club/edit/<club_id>', views.entrys_club_edit, name='entrys_club_edit'),
    path('<event_id>/entrys/club/merge/<club1_id>/<club2_id>', views.entrys_club_merge, name='entrys_club_merge'),
    path('<event_id>/entrys/meldungen/', views.entrys_entry_list, name='entrys_entry_list'),
    path('<event_id>/starts/', views.start, name='start'),
    path('<event_id>/starts/competition/', views.competition_list, name='competition_list'),
    path('<event_id>/starts/competition/?del=<competition_id>', views.del_singlecompetition, name='del_singlecompetition'),
    path('<event_id>/starts/competition/?merge=<competition_id>', views.merge_singlecompetition, name='merge_singlecompetition'),
    path('<event_id>/starts/competition/calc_entry', views.competition_list, name='competition_list'),
    path('<event_id>/starts/startnr/', views.start_startnr, name='start_startnr'),
    path('<event_id>/starts/startnr?del=<person_id>', views.startnr_clr, name='startnr_clr'),
    path('<event_id>/starts/seeding/', views.start_seed_overview, name='start_seed_overview'),
    path('<event_id>/starts/seeding/<discipline_id>', views.start_seed_listview, name='start_seed_listview'),
    path('<event_id>/execution/', views.execution, name='execution'),
    path('<event_id>/execution/results/show/<scoringcat_id>/<discipline_id>', views.execution_show_result, name='execution_show_result'),
    path('<event_id>/execution/results/edit/<competition_id>', views.execution_edit_result, name='execution_edit_result'),
    path('<event_id>/execution/results/import/', views.import_result_csv, name='import_result_csv'),
    path('<event_id>/execution/results/print_resultlist/<scoringcat_id>/<discipline_id>', views.print_resultlist, name='print_resultlist'),
    path('<event_id>/execution/results/print_compcert/<club_id>', views.print_compcert_pdf, name='print_compcert_pdf'),
    path('pdf/', views.generate_pdf, name='generate_pdf'),
    path('urkunde/', views.generate_certificate_pdf, name='generate_certificate_pdf'),
    path('<event_id>/infield/iuf/<start_id>', views.infield_iuf_slalom, name='infield_iuf_slalom'),
    path('infield_serialsend', views.infield_serialsend, name='infield_serialsend'),
    path('infield_serialread', views.infield_serialread, name='infield_serialread'),
]

#(?P<pk>\d+)/$

vunireg/views/filters.py
import django_filters
from django import forms
from vunireg.models import Person, Club, Entry, Competition

class PersonFilter(django_filters.FilterSet):

    class Meta:
        model = Person
        fields = {'forename': ['icontains',],
                  'surname': ['icontains',],
                  'gender': ['exact',],
                  'dateofbirth': ['gt',],
                  'club': ['exact',],
                 }
            

class ClubFilter(django_filters.FilterSet):

    class Meta:
        model = Club
        fields = '__all__'
        fields = {'clubname': ['icontains',],
                  'individualstart': ['exact',],
                 }


class EntryFilter(django_filters.FilterSet):
    discipline = django_filters.CharFilter(field_name='discipline__name')
    competition = django_filters.CharFilter(field_name='competition__fullname')
    forename = django_filters.CharFilter(field_name='person__forename')
    surname = django_filters.CharFilter(field_name='person__surname')
    gender = django_filters.CharFilter(field_name='person__gender')
    club = django_filters.CharFilter(field_name='person__club__clubname')

    class Meta:
        model = Entry
        fields = '__all__'
        fields = {'discipline': ['exact',],
                  'competition': ['exact',],
                  'forename': ['icontains',],
                  'surname': ['icontains',],
                  'gender': ['exact',],
                  'club': ['icontains',],
                 }
             
                 
class CompetitionFilter(django_filters.FilterSet):
#    maxage__gt = django_filters.NumberFilter(field_name='maxage', lookup_expr='gt')
#    maxage__lt = django_filters.NumberFilter(field_name='maxage', lookup_expr='lt')

    class Meta:
        model = Competition
        fields = '__all__'
        fields = {'discipline': ['exact',],
                  'fullname': ['icontains',],
                  'maxage': ['gt','lt',],
                  'gender': ['exact',],
                  'entrycount': ['gt',],
                 }

vunireg/views/views_entrys.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
import datetime
import csv
import types
from django.db.models import F, Func

from django.template.loader import render_to_string
from django.conf import settings
#from weasyprint import HTML, CSS
import tempfile

from vunireg.models import Event, Person, Team, Club, Entry, Discipline, Agegroup, Competition, Start, Scoringcategory, Qualification, Result
from .filters import PersonFilter, ClubFilter, EntryFilter, CompetitionFilter
from .forms import PersonEditForm, EntryEditInlineForm, TeamEditForm, ClubEditForm



# Funktion, zur Ausgabe der Übersichtsseite für den Bereich Meldungen
def entrys(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    response = ''
    error = ''
    entry_query = Entry.objects.filter(event__id=event.pk)
    person_query = Person.objects.filter(entry__in=entry_query).distinct()
    club_query = Club.objects.filter(person__in=person_query).distinct()
    participans = types.SimpleNamespace()
    participans.total = person_query.count()
    participans.male = person_query.filter(gender='m').count()
    participans.female = person_query.filter(gender='f').count()
#    participans.U15total = person_query.count()
#    participans.U15male = person_query.filter(gender='m').count()
#    participans.U15female = person_query.filter(gender='f').count()
#    participans.15UPtotal = person_query.count()
#    participans.15UPmale = person_query.filter(gender='m').count()
#    participans.15UPfemale = person_query.filter(gender='f').count()
    entrys = types.SimpleNamespace()
    entrys.single = entry_query.filter(discipline__isgroupdisc=1).count()
    entrys.relay = entry_query.filter(team__isnull=False).count()
    entrys.total = entrys.single + entrys.relay
    clubs = types.SimpleNamespace()
    clubs.total = club_query.count()
    # Ausgabe
    content = {
        "participans":participans, "entrys":entrys, 'clubs':clubs, 'error':error, 'response':response, 'event':event,
    }
    return render(request, "vunireg/entrys_overview.html", content)

# Funktion, zur Ausgabe der Seite zum Verwalten der Teilnehmer
def person_list(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    response = ''
    error = ''
    entry_query = Entry.objects.filter(event__id=event.pk)
    person_query = Person.objects.filter(entry__in=entry_query).distinct()
    person_filter = PersonFilter(request.GET, queryset = person_query)
    # Ausgabe
    content = {
        'filter':person_filter, 'error':error, 'response':response, 'event':event,
    }
    return render(request, 'vunireg/entrys_person_list.html', content)
    
# Funktion, zur Ausgabe der Seite zum Verwalten der Teams
def entrys_team_list(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    response = ''
    error = ''
    entry_query = Entry.objects.filter(event__id=event.pk)
    team_query = Team.objects.filter(event__id=event.pk)
    # Teams anhand der Meldungen automatisch erstellen
    if(request.GET.get('update_teams')):
        entrys_update_teams(event.pk)
        response += 'Alle Teams wurden auf Basis der Meldungen aktualisiert!' + '</br>'
        # Warnmeldung ausgeben, falls es noch Staffel-Meldungen gibt, die keiner Staffel zugeordnet sind
        entrys_for_teams_query = entry_query.filter(discipline__isgroupdisc__gt=1, person__isnull=False)
        competition_error = len(entrys_for_teams_query.filter(entry_team=None))
        if competition_error == 0:
            response += 'Alle Einzel-Meldungen für eine Staffel sind einem Staffel-Team zugeordnet.' + '</br>'
    # Für jede Staffel die aktuelle Teilnehmerzahl ermitteln
    for team in team_query:
        team.members = team.team_entries.count()
    # Warnmeldung ausgeben, falls es noch Staffel-Meldungen gibt, die keiner Staffel zugeordnet sind
    entrys_for_teams_query = entry_query.filter(discipline__isgroupdisc__gt=1, person__isnull=False)
    competition_error = len(entrys_for_teams_query.filter(entry_team=None))
    if competition_error > 0:
        error += 'ACHTUNG: Es gibt noch ' + str(competition_error) + ' Einzel-Meldung(en) für eine Staffel, die keinem Staffel-Team zugeordnet ist/sind!' + '<br />'
    # Ausgabe
    content = {
        'team_list':team_query, 'error':error, 'response':response, 'event':event,
    }
    return render(request, 'vunireg/entrys_team_list.html', content)

# Funktion, zur Ausgabe der Seite zum Verwalten der Vereine
def club_list(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    response = ''
    error = ''
    entry_query = Entry.objects.filter(event__id=event.pk)
    person_query = Person.objects.filter(entry__in=entry_query).distinct()
    club_query = Club.objects.filter(person__in=person_query).distinct()
    # Anzahl der Teilnehmer & Anzahl der Meldungen pro Verein ermitteln
    for club in club_query:
        club.participants = len(person_query.filter(club=club))
        club.entrys = len(entry_query.filter(person__club=club))
    # Ausgabe
    content = {
        "club_list": club_query, 'error':error, 'response':response, 'event':event,
    }
    return render(request, "vunireg/entrys_club_list.html", content)

# Funktion, zur Ausgabe einer Liste aller Meldungen
def entrys_entry_list(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    response = ''
    error = ''
    #    entry_list = Entry.objects.all()
    entry_list = Entry.objects.filter(event__id=event.pk).order_by('person__club', 'person__surname', 'person__forename')
    entry_filter = EntryFilter(request.GET, queryset = entry_list)
    # Ausgabe
    content = {
        'filter':entry_filter, "entry_list":entry_list, 'error':error, 'response':response, 'event':event,
    }
    return render(request, "vunireg/entrys_entry_list.html", content)

# Funktion, die das Hinzufügen einzelner oder mehrerer Meldungen und Teilnehmer per CSV Datei ermöglicht
def person_csv(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    csvfile = request.POST.get('csvfile', False)
    response = ''
    error = ''
    text = ''
    if csvfile:
        n = 0
        for row in csvfile.splitlines():
            data = row.split(',')
            txt = ''
            n += 1
            datacount = len(data)
            # Es werden mindestens 6 Elemente in der Eingabe benötigt, um einen gültigen Teilnehmer anzulegen
            if datacount < 6:
                error += 'ERROR: Die Eingabe in Reihe ' + str(n) + ' enthält zu wenig Daten'
                text += 'ERROR: Die Eingabe enthält zu wenig Daten\r\n'
                text += ','.join(data) + '\r\n'
                break

            # überprüfen, ob Verein vorhanden
            try:
                v = Club.objects.get(clubname__iexact=data[5])
                txt += 'Verein vorhanden - '
            except Club.DoesNotExist:
                txt += 'Verein nicht vorhanden - '
                if data[5] == '':
                    v = Club(clubname=('vereinslos_' + data[0]), individualstart=True)
                    v.save()
                else:
                    v = Club(clubname=data[5], individualstart=False)
                    v.save()

            # überprüfen, ob Teilnehmer vorhanden
            try:
                t = Person.objects.get(surname__iexact=data[0], forename__iexact=data[1], dateofbirth=data[3])
                txt += 'Teilnehmer vorhanden - '
            except Person.DoesNotExist:
                txt += 'Teilnehmer nicht vorhanden - '
                t = Person(surname=data[0], forename=data[1], gender=data[2], dateofbirth=data[3], custom1=data[4], club=v)
                t.save()

            # Bei mehr als 6 Elementen werden zusätzlich zu den Teilnehmerdaten noch Meldungen übergeben
            if datacount > 6:
                i = 0
                while i < (datacount-6):
                    i += 1
                    # überprüfen, ob Disziplin vorhanden
                    try:
                        d = Discipline.objects.get(name__iexact=data[(5+i)])
                        txt += 'Disziplin vorhanden - '
                    except Discipline.DoesNotExist:
                        try:
                            d = Discipline.objects.get(code__iexact=data[(5+i)])
                            txt += 'Disziplin vorhanden - '
                        except Discipline.DoesNotExist:
                            error += 'ERROR: Die Disziplin ' + data[(5+i)] + ' ist nicht bekannt!'
                            text += 'ERROR: Die Disziplin ' + data[(5+i)] + ' ist nicht bekannt!\r\n'
                            break
                   #     d = Discipline(name=data[(5+i)], group=0, ranking=0)
                   #     d.save()
                    i += 1
                    # überprüfen, ob Meldung vorhanden
                    try:
                        m = Entry.objects.get(event=event, person=t, discipline=d)
                        if m.value==data[(5+i)]:
                            txt += 'Meldung breits vorhanden!'
                        else:
                            m.value=data[(5+i)]
                            m.save()
                            txt += 'Meldung breits vorhanden, Meldezeit aktualisiert!'
                    except Entry.DoesNotExist:
                        txt += 'Meldung noch nicht vorhanden & angelegt!'
                        m = Entry(event=event, person=t , discipline=d, value=data[(5+i)])
                        m.save()
                    
                    text += txt + '\r\n'
                    text += ','.join(data) + '\r\n'
                    txt = ''
            else:
                text += txt + '\r\n'
                text += ','.join(data) + '\r\n'
    # Ausgabe
    content = {
        'text':text, 'error':error, 'response':response, 'event':event,
    }

vunireg/templates/vunireg/entrys_club_edit_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="container">

    <div class="row">
        <h2>{{ text.heading }}</h2>
    </div>
    
    <div class="row wide">
        {# Include individual errors und responses #}
        {% if not error == '' %}
        <div class="response-field error">
            <p>{{ error|safe  }}</p>
        </div>
        {% endif %}
        {% if not response == '' %}
        <div class="response-field">
            <p>{{ response|safe  }}</p>
        </div>
        {% endif %}
    </div>
 
 <!--
        <fieldset>
            Datenbank-Schnellnavigation
            <div class="button"><a href="{% url 'vunireg:person_add' event_id=event.pk %}">NEW</a></div>
            <div class="button"><a href="#">Previous</a></div>
            <div class="button"><a href="#">Next</a></div>
            <div class="button"><a href="{% url 'vunireg:person_list' event_id=event.pk %}">Zurück zur Übersicht</a></div>
        </fieldset>
--!>
        
    <div class="row">
        <form class="edit-form clearfix" action="" method="POST">
        {% csrf_token %}
            <fieldset class="wide">
            
                {# Include non_form_errors of form #}
                {{ club_form.non_field_errors }}
            
                {# Include hidden fields of form #}
                {% for hidden_field in club_form.hidden_fields %}
                    {{ hidden_field }}
                    {{ hidden_field.errors }}
                {% endfor %}

                <div class="row clearfix">
                    <div class="form-col1">
                        <label class="visible" for="{{ pform.forename.id_for_label }}">Vereinsname</label>
                    </div>
                    <div class="form-col2" >
                        {{ club_form.clubname }}
                        {{ club_form.clubname.errors }}
                    </div>
                </div>
                <div class="row clearfix">
                    <div class="form-col1">
                        <label class="visible" for="{{ pform.surname.id_for_label }}">Einzelstarter</label>
                    </div>
                    <div class="form-col2" >
                        {{ club_form.individualstart }}
                        {{ club_form.individualstart.errors }}
                    </div>
                </div>
                
                <div class="sep-line"></div>
                
                <div class="row clearfix">
                    <div class="form-col">
                        <h3>Details Ansprechpartner</h3>
                    </div>
                </div>
                
                <div class="row clearfix">
                    <div class="form-col1">
                        <label class="visible" for="{{ pform.surname.id_for_label }}">Kontaktperson</label>
                    </div>
                    <div class="form-col2" >
                        {{ club_form.contactperson }}
                        {{ club_form.contactperson.errors }}
                    </div>
                </div>
            
                <div class="sep-line"></div>

                <div class="row clearfix bottom pull-right">
                    <div class="form-col">
                        <button class="button" type="submit" value="save_club">Verein speichern</button>
                    </div>
                    <div class="form-col">
                        <div class="button"><a href="{% url 'vunireg:club_list' event_id=event.pk %}">Abbrechen</a></div>
                    </div>
                </div>
                <div class="row bottom">
                    <div class="delete">
                        <a class="button" href="#popup1">Löschen</a>
                    </div>
                    <div id="popup1" class="overlay">
                        <div class="popup">
                            <h2>ACHTUNG</h2>
                            <div class="popuptext">
                                Sind Sie sicher, dass sie den Verein "{{ club_form.clubname }}" löschen möchten?
                            </div>
                            <div class="clearfix">
                                <div class="popupbtn deletebtn"><a href="">Verein löschen</a></div>
                                <div class="popupbtn cancelbtn"><a href="#">Abbrechen</a></div>
                            </div>
                        </div>
                    </div>
                </div>

            </fieldset>
        </form>  
    </div>
    
</div>
{% endblock %}

vunireg/templates/vunireg/entrys_overview.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="container">

    <div class="row">
        <h2>Übersicht Meldungen</h2>
    </div>

    <div class="row wide">
        {# Include individual errors und responses #}
        {% if not error == '' %}
        <div class="response-field error">
            <p>{{ error|safe  }}</p>
        </div>
        {% endif %}
        {% if not response == '' %}
        <div class="response-field">
            <p>{{ response|safe  }}</p>
        </div>
        {% endif %}
    </div>
     
    <div class="row">
        <h3>Meldungen Importieren</h3>
        <fieldset class="wide">
            <div class="row clearfix bottom">
                <div class="form-col">
                    <div class="button fixed-width">
                        <a style="display:block" href="{% url 'vunireg:person_csv' event_id=event.pk %}">Meldungen per CSV importieren</a>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
    
    <div class="row">
        <h3>Zusammenfassung</h3>
        <fieldset class="wide">
            
            <div class="row clearfix">
                <div class="col1" style="margin: auto; text-align:center;">
                    {% if entrys.total > 0 %}
                    <h3>Meldungen</h3>
                    <table class="fieldset-list">
                        <thead>
                            <tr>
                                <th style="width:50px;">
                                </th>
                                <th style="width:80px; text-align:center">
                                    Einzelstarts
                                </th>
                                <th style="width:80px; text-align:center">
                                    Staffeln
                                </th>
                                <th style="width:80px; text-align:center">
                                    Gesamt
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ entrys.single }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ entrys.relay }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ entrys.total }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    {% else %}
                    <h3>Es gibt für diesen Wettkampf noch keine Meldungen!</h3>
                    {% endif %}
                </div>
            </div>

            <div class="sep-line"></div>

            <div class="row clearfix">
                <div class="col1" style="margin: auto; text-align:center;">
                    {% if participans.total > 0 %}
                    <h3>Teilnehmer</h3>
                    <table class="fieldset-list">
                        <thead>
                            <tr>
                                <th style="width:50px;">
                                </th>
                                <th style="width:80px; text-align:center">
                                    Männlich
                                </th>
                                <th style="width:80px; text-align:center">
                                    Weiblich
                                </th>
                                <th style="width:80px; text-align:center">
                                    Gesamt
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    U15
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.U15male }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.U15female }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.U15total }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    15+
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.15UPmale }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.15UPfemale }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.15UPtotal }}
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Gesamt
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.male }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.female }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    {{ participans.total }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    {% else %}
                    <h3>Es gibt für diesen Wettkampf noch keine Teilnehmer!</h3>
                    {% endif %}  
                </div>
            </div>
            
            <div class="sep-line"></div>
            
            <div class="row clearfix bottom">
                <div class="col1" style="margin: auto; text-align:center;">
                    {% if clubs.total > 0 %}
                    <h3>Vereine</h3>
                    <table class="fieldset-list">
                        <thead>
                            <tr>
                                <th style="width:80px;">
                                    
                                </th>
                                <th style="width:50px; text-align:center">
                                    Gesamt
                                </th>
                                <td style="width:80px; text-align:center">
                                    {{ clubs.total }}
                                </td>
                                <td style="width:80px; text-align:center">
                                    
                                </td>
                            </tr>
                        </thead>
                    </table>
                    {% else %}
                    <h3>Es gibt für diesen Wettkampf noch keine Vereine!</h3>
                    {% endif %}  
                </div>
            </div>

        </fieldset>
    </div>
    
    <div class="row">
        <h3>Teilnehmer, Teams und Vereine verwalten</h3>
        <fieldset class="wide">
            <div class="row bottom">
                <div class="form-col">
                    <div class="button fixed-width">
                        <a style="display:block" href="{% url 'vunireg:person_list' event_id=event.pk %}">Teilnehmer verwalten</a>
                    </div>
                </div>
                <div class="form-col">
                    <div class="button fixed-width">
                        <a style="display:block" href="{% url 'vunireg:entrys_team_list' event_id=event.pk %}">Staffeln verwalten</a>
                    </div>
                </div>
                <div class="form-col">
                    <div class="button fixed-width">
                        <a style="display:block" href="{% url 'vunireg:club_list' event_id=event.pk %}">Vereine verwalten</a>
                    </div>
                </div>
            </div>  
        </fieldset>
    </div>
    
    <div class="row">
        <h3>Übersicht Meldungen</h3>
        <fieldset class="wide">
            <div class="row bottom">
                <div class="form-col">
                    <div class="button fixed-width">
                        <a style="display:block" href="{% url 'vunireg:entrys_entry_list' event_id=event.pk %}">Übersicht Meldungen</a>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
    
    <div class="row space"></div>
    
</div>
{% endblock %}

vunireg/templates/vunireg/start_seed_overview.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="container">

    <div class="row">
        <h2>Starts setzten</h2>
    </div>

    <div class="row">
        {# Include individual errors und responses #}
        {% if not error == '' %}
        <div class="response-field error">
            <p>{{ error|safe  }}</p>
        </div>
        {% endif %}
        {% if not response == '' %}
        <div class="response-field">
            <p>{{ response|safe  }}</p>
        </div>
        {% endif %}
    </div>

    <div class="row">
        <div class="sub-nav-top">
            <ul id="sub-menu" class="no-list">
                <li>
                    <a href="{% url 'vunireg:start_seed_overview' event_id=event.pk %}">Übersicht</a>
                </li>
            </ul>
            <ul id="sub-menu" class="no-list">
                {% for discipline in disciplinequery %}
                <li>
                    {% if discipline.state == 'NOENTRYS' %}
                    <div class="colorpick"></div>
                    {% elif discipline.state == 'NOSTARTS' %}
                    <div class="colorpick yellow"></div>
                    {% elif discipline.state == 'STARTSOK' %}
                    <div class="colorpick green"></div>
                    {% else %}
                    <div class="colorpick red"></div>
                    {% endif %}
                    <a href="{% url 'vunireg:start_seed_listview' event_id=event.pk discipline_id=discipline.pk %}">{{ discipline }}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>   
    
    <div class="row space"></div>

 </div>
{% endblock %}